// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAHWHXSxWSYpZt455-Xm2cP4KWpZty0bk',
    appId: '1:1651191256:web:1b911c2b121312cb7916ad',
    messagingSenderId: '1651191256',
    projectId: 'crudtutorial-72902',
    authDomain: 'crudtutorial-72902.firebaseapp.com',
    storageBucket: 'crudtutorial-72902.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNeJENmWidy2zpGoDdoUqX2sjg8aV8Do4',
    appId: '1:1651191256:android:cfee061aaf0bc8ba7916ad',
    messagingSenderId: '1651191256',
    projectId: 'crudtutorial-72902',
    storageBucket: 'crudtutorial-72902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMUc2Z3UY_ujeR-Q897Tl7B4sUtDI7L3k',
    appId: '1:1651191256:ios:6f8ba0b40d23dd7d7916ad',
    messagingSenderId: '1651191256',
    projectId: 'crudtutorial-72902',
    storageBucket: 'crudtutorial-72902.firebasestorage.app',
    iosBundleId: 'com.example.crudtutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMUc2Z3UY_ujeR-Q897Tl7B4sUtDI7L3k',
    appId: '1:1651191256:ios:6f8ba0b40d23dd7d7916ad',
    messagingSenderId: '1651191256',
    projectId: 'crudtutorial-72902',
    storageBucket: 'crudtutorial-72902.firebasestorage.app',
    iosBundleId: 'com.example.crudtutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAHWHXSxWSYpZt455-Xm2cP4KWpZty0bk',
    appId: '1:1651191256:web:05330aa71476569e7916ad',
    messagingSenderId: '1651191256',
    projectId: 'crudtutorial-72902',
    authDomain: 'crudtutorial-72902.firebaseapp.com',
    storageBucket: 'crudtutorial-72902.firebasestorage.app',
  );
}
